import type { Metadata } from "next";
import { Barlow, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: "600",
});

const openSans = Open_Sans({
  variable: "--font-open_sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${barlow.variable} ${openSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
